### ISSUE TITLE
Add hardware wallet support

### ISSUE THREAD

**Issue by jalehman** [urbit/bitcoin-wallet#30]
Christian knows someone that can tell us what best practices are for doing browser-based hw wallet authentication.

We could do variants of this, e.g. QR code signing, but directly hooking up Ledger & Trezor is the critical path.

**Comment by timlucmiptev** [comment]
So I've investigated this for a more general solution in the browser, and unfortunately Liquality (which *does* have extension Bitcoin support) doesn't expose the xpub of its wallet or let you input that.  WalletConnect is just for dapps.

Think we should focus on Trezor+Ledger via USB from the browser, and then can later add a QR/PSBT flow for the newer generation of more "manual" cold wallets like ColdCard.

**Comment by Quaternioneer** [comment]
+1 Transacting without navigating to Bridge would be a much more convenient user experience.

**Comment by finned-palmer** [comment]
Because WebUSB requires a secure context (HTTPS, https://developer.mozilla.org/en-US/docs/Web/API/WebUSB_API), and because almost all of urbit's users currently use landscape outside of a secure context, this is unfortunately not going to happen now. 

PSBTs are, however, being implemented (a separate PR is open for that: https://github.com/urbit/urbit/pull/5127), and any hardware wallet that supports PSBTs should work. Right now, for "out-of-the-box" support for PSBTs, you would need a Coldcard or Cobo Vault. Other wallets (Ledger, Trezor) could be used via Bitcoin's Hardware Wallet Interface (HWI) either directly in Bitcoin Core or via other wallets that support HWI (Wasabi, for instance).

Our thinking is that in the long term most people won't really want to use a hardware wallet as a hot wallet on urbit anyway, especially as on-chain fees go up and the lightning network continues to mature (most will probably just use lightning for their hot wallet anyway). For those who might want to do that, they will have the PSBT option.

If we implement hot signing in urbit in the future, we may be able to revisit this (implementing HWI in btc-wallet, basically).
